// web-components/src/CodeSnippet.ts
import * as LucideIcons from 'lucide-static'
import { icon } from './icons'

const TAG_NAME = 'tc-code-snippet'

export type CodeSnippetLanguage = 'javascript' | 'typescript' | 'bash'
const LANGUAGES: CodeSnippetLanguage[] = ['javascript', 'typescript', 'bash']

function esc(s: string): string {
    return s
        .replace(/&/g, '&amp;')
        .replace(/</g, '&lt;')
        .replace(/>/g, '&gt;')
}

function lucideIcon(name: string): string {
    const pascal = name
        .split('-')
        .map(p => p.charAt(0).toUpperCase() + p.slice(1))
        .join('')
    const svg = (LucideIcons as Record<string, string>)[pascal]
    return svg ? icon(svg) : ''
}

const copyIconHtml = lucideIcon('copy')
const checkIconHtml = lucideIcon('check')

// Token regex sources — order within alternation determines priority.
// Defined as string fragments to avoid module-level regex statefulness
// (each call to applyHighlight creates a fresh /g regex).
const JS_TOKEN_SRC =
    '(\\/\\/[^\\n]*)' +                     // (1) single-line comment
    '|(\\/\\*[\\s\\S]*?\\*\\/)' +           // (2) block comment
    '|(`(?:[^`\\\\]|\\\\.)*`)' +            // (3) template literal
    '|("(?:[^"\\\\]|\\\\.)*")' +            // (4) double-quoted string
    "|(\'(?:[^\'\\\\]|\\\\.)*\')" +         // (5) single-quoted string
    '|(\\b\\d+(?:\\.\\d+)?(?:[eE][+-]?\\d+)?\\b)' + // (6) number
    '|(\\b(?:const|let|var|function|return|if|else|for|while|class|new|typeof|instanceof|this|import|export|default|from|as|async|await|try|catch|finally|throw|true|false|null|undefined|void|break|continue|switch|case|of|in|do|extends|super|static|get|set|yield|delete|interface|type|enum|namespace|abstract|implements|public|private|protected|readonly|declare)\\b)' // (7) keyword

const BASH_TOKEN_SRC =
    '(#[^\\n]*)' +                          // (1) comment
    '|("(?:[^"\\\\]|\\\\.)*")' +            // (2) double-quoted string
    "|(\'[^\']*\')" +                        // (3) single-quoted string (no escapes in bash)
    '|(\\$(?:\\{[^}]*\\}|\\([^)]*\\)|[a-zA-Z_][a-zA-Z0-9_]*|\\d+))' + // (4) variable
    '|(\\b\\d+\\b)' +                        // (5) number
    '|(\\b(?:if|then|else|elif|fi|for|do|done|while|until|echo|cd|ls|export|source|function|return|case|esac|in|exit|true|false|break|continue|shift|unset|set|local|mkdir|cp|mv|rm|cat|grep|sed|awk|curl|wget|git|npm|yarn|chmod|chown|sudo|apt|brew|pip|python|python3|node|bash|sh)\\b)' // (6) keyword

function applyHighlight(code: string, language: CodeSnippetLanguage): string {
    const escaped = esc(code)

    if (language === 'javascript' || language === 'typescript') {
        return escaped.replace(
            new RegExp(JS_TOKEN_SRC, 'g'),
            (match, cline, cblock, tmpl, dbl, sgl, num, kw) => {
                if (cline !== undefined || cblock !== undefined) return `<span class="tok-comment">${match}</span>`
                if (tmpl !== undefined || dbl !== undefined || sgl !== undefined) return `<span class="tok-string">${match}</span>`
                if (num !== undefined) return `<span class="tok-number">${match}</span>`
                if (kw !== undefined) return `<span class="tok-keyword">${match}</span>`
                return match
            }
        )
    }

    if (language === 'bash') {
        return escaped.replace(
            new RegExp(BASH_TOKEN_SRC, 'g'),
            (match, comment, dbl, sgl, vari, num, kw) => {
                if (comment !== undefined) return `<span class="tok-comment">${match}</span>`
                if (dbl !== undefined || sgl !== undefined) return `<span class="tok-string">${match}</span>`
                if (vari !== undefined) return `<span class="tok-variable">${match}</span>`
                if (num !== undefined) return `<span class="tok-number">${match}</span>`
                if (kw !== undefined) return `<span class="tok-keyword">${match}</span>`
                return match
            }
        )
    }

    return escaped
}

const SKEL_WIDTHS = ['60%', '85%', '70%', '45%', '90%', '55%']

export class CodeSnippet extends HTMLElement {
    private _initialised = false
    private _copied = false
    private _copyTimer: ReturnType<typeof setTimeout> | null = null

    /** Optional copy callback — called with the copied code string after a successful write. */
    onCopy: ((code: string) => void) | null = null

    static get observedAttributes(): string[] {
        return ['code', 'language', 'title', 'show-copy-button', 'loading']
    }

    constructor() {
        super()
    }

    connectedCallback(): void {
        if (!this._initialised) {
            // Slotted text-content fallback: capture textContent as code when
            // no code attribute is present (e.g. <tc-code-snippet>…</tc-code-snippet>).
            if (!this.hasAttribute('code')) {
                const text = this.textContent?.trim() ?? ''
                if (text) this.setAttribute('code', text)
            }
            this.render()
            this.addEventListener('click', this._onHostClick)
            this._initialised = true
        }
    }

    disconnectedCallback(): void {
        this.removeEventListener('click', this._onHostClick)
        if (this._copyTimer !== null) {
            clearTimeout(this._copyTimer)
            this._copyTimer = null
        }
    }

    attributeChangedCallback(): void {
        if (!this.isConnected || !this._initialised) return
        this.render()
    }

    get code(): string {
        return this.getAttribute('code') ?? ''
    }
    set code(v: string) {
        this.setAttribute('code', v)
    }

    get language(): CodeSnippetLanguage {
        const v = this.getAttribute('language') as CodeSnippetLanguage
        return LANGUAGES.includes(v) ? v : 'javascript'
    }
    set language(v: CodeSnippetLanguage) {
        this.setAttribute('language', v)
    }

    // title reflects the native HTMLElement.title attribute — no override needed.

    get showCopyButton(): boolean {
        const v = this.getAttribute('show-copy-button')
        return v !== 'false'
    }
    set showCopyButton(v: boolean) {
        if (!v) this.setAttribute('show-copy-button', 'false')
        else this.removeAttribute('show-copy-button')
    }

    get loading(): boolean {
        return this.hasAttribute('loading')
    }
    set loading(v: boolean) {
        if (v) this.setAttribute('loading', '')
        else this.removeAttribute('loading')
    }

    private _onHostClick = (e: Event) => {
        const target = e.target as Element
        if (!target.closest('.tc-code-snippet-copy')) return
        void this._handleCopy()
    }

    private async _handleCopy(): Promise<void> {
        const code = this.getAttribute('code') ?? ''
        try {
            await navigator.clipboard.writeText(code)
        } catch {
            return
        }

        this.dispatchEvent(new CustomEvent('tc-copy', {
            bubbles: true,
            composed: true,
            detail: { code },
        }))
        if (typeof this.onCopy === 'function') this.onCopy(code)

        this._setCopied(true)
        if (this._copyTimer !== null) clearTimeout(this._copyTimer)
        this._copyTimer = setTimeout(() => {
            this._setCopied(false)
            this._copyTimer = null
        }, 1500)
    }

    private _setCopied(copied: boolean): void {
        this._copied = copied
        const btn = this.querySelector<HTMLButtonElement>('.tc-code-snippet-copy')
        const status = this.querySelector<HTMLElement>('.tc-code-snippet-status')

        if (btn) {
            if (copied) {
                btn.innerHTML = `${checkIconHtml}<span class="tc-code-snippet-copy-lbl" aria-hidden="true">Copied</span>`
                btn.setAttribute('aria-label', 'Copied')
                btn.classList.add('tc-code-snippet-copy--copied')
            } else {
                btn.innerHTML = `${copyIconHtml}<span class="tc-code-snippet-copy-lbl" aria-hidden="true"></span>`
                btn.setAttribute('aria-label', 'Copy code')
                btn.classList.remove('tc-code-snippet-copy--copied')
            }
        }

        if (status) status.textContent = copied ? 'Copied' : ''
    }

    private render(): void {
        const code = this.getAttribute('code') ?? ''
        const language = this.language
        const titleAttr = this.getAttribute('title')
        const showCopyButton = this.showCopyButton
        const loading = this.hasAttribute('loading')

        if (loading) {
            this.innerHTML =
                `<div class="tc-code-snippet tc-code-snippet--loading" aria-busy="true">` +
                    `<div class="tc-code-snippet-skel">` +
                        SKEL_WIDTHS.map(w => `<div class="tc-code-snippet-skel-line" style="width:${w}"></div>`).join('') +
                    `</div>` +
                `</div>`
            return
        }

        const titleText = titleAttr != null ? esc(titleAttr) : language.toUpperCase()
        const showHeader = titleAttr != null || showCopyButton

        const copyBtnHtml = showCopyButton
            ? `<button class="tc-code-snippet-copy${this._copied ? ' tc-code-snippet-copy--copied' : ''}" ` +
              `type="button" aria-label="${this._copied ? 'Copied' : 'Copy code'}">` +
              `${this._copied ? checkIconHtml : copyIconHtml}` +
              `<span class="tc-code-snippet-copy-lbl" aria-hidden="true">${this._copied ? 'Copied' : ''}</span>` +
              `</button>`
            : ''

        const headerHtml = showHeader
            ? `<div class="tc-code-snippet-header">` +
              `<span class="tc-code-snippet-title">${titleText}</span>` +
              copyBtnHtml +
              `</div>`
            : ''

        const highlightedCode = applyHighlight(code, language)

        this.innerHTML =
            `<div class="tc-code-snippet">` +
                headerHtml +
                `<pre class="tc-code-snippet-pre"><code class="tc-code-snippet-code language-${esc(language)}">${highlightedCode}</code></pre>` +
                `<div class="tc-code-snippet-status" role="status" aria-live="polite"></div>` +
            `</div>`
    }
}

declare global {
    interface HTMLElementTagNameMap {
        [TAG_NAME]: CodeSnippet
    }
}

// react-components/src/CodeSnippet.tsx
import React, { useState, useCallback, useMemo, Fragment } from 'react'
import { Icon } from './Icon'
import { Skeleton } from './Skeleton'

export type CodeSnippetLanguage = 'javascript' | 'typescript' | 'bash'

export interface CodeSnippetProps extends Omit<React.HTMLAttributes<HTMLDivElement>, 'children' | 'onCopy'> {
	code: string
	language?: CodeSnippetLanguage
	onCopy?: (code: string) => void
	showCopyButton?: boolean
	title?: string
	loading?: boolean
}

const languageLabels: Record<CodeSnippetLanguage, string> = {
	javascript: 'JavaScript',
	typescript: 'TypeScript',
	bash: 'Bash',
}

type TokenType =
	| 'comment'
	| 'string'
	| 'keyword'
	| 'literal'
	| 'number'
	| 'function'
	| 'variable'
	| 'flag'
	| 'operator'
	| 'punctuation'
	| 'plain'

interface Token {
	type: TokenType
	value: string
}

const JS_KEYWORDS = new Set([
	'const', 'let', 'var', 'function', 'return', 'if', 'else', 'for', 'while',
	'do', 'switch', 'case', 'break', 'continue', 'default', 'try', 'catch',
	'finally', 'throw', 'new', 'class', 'extends', 'super', 'this', 'import',
	'export', 'from', 'as', 'async', 'await', 'yield', 'typeof', 'instanceof',
	'in', 'of', 'void', 'delete', 'static', 'get', 'set',
])

const JS_LITERALS = new Set(['null', 'undefined', 'true', 'false', 'NaN', 'Infinity'])

const TS_KEYWORDS = new Set([
	'interface', 'type', 'enum', 'namespace', 'module', 'declare', 'public',
	'private', 'protected', 'readonly', 'abstract', 'implements', 'is',
	'keyof', 'infer', 'satisfies',
])

const TS_TYPES = new Set([
	'any', 'unknown', 'never', 'string', 'number', 'boolean', 'object',
	'symbol', 'bigint',
])

const BASH_KEYWORDS = new Set([
	'if', 'then', 'else', 'elif', 'fi', 'for', 'while', 'until', 'do', 'done',
	'case', 'esac', 'in', 'function', 'return', 'export', 'local', 'readonly',
	'break', 'continue', 'declare', 'exit', 'set', 'unset', 'source', 'alias', 'eval',
])

const BASH_BUILTINS = new Set([
	'echo', 'cd', 'pwd', 'ls', 'cp', 'mv', 'rm', 'mkdir', 'rmdir', 'touch',
	'cat', 'grep', 'sed', 'awk', 'find', 'sort', 'uniq', 'head', 'tail',
	'curl', 'wget', 'git', 'npm', 'npx', 'yarn', 'pnpm', 'node', 'python',
	'pip', 'sudo', 'chmod', 'chown', 'tar', 'gzip', 'zip', 'unzip', 'ssh',
	'scp', 'docker', 'kubectl', 'make', 'bash', 'sh', 'env', 'which', 'man',
])

const JS_PATTERN =
	/(\/\/[^\n]*|\/\*[\s\S]*?\*\/)|('(?:\\.|[^'\\])*'|"(?:\\.|[^"\\])*"|`(?:\\.|[^`\\])*`)|(\b0x[\da-fA-F]+\b|\b\d+(?:\.\d+)?(?:e[+-]?\d+)?n?\b)|([A-Za-z_$][\w$]*)|([+\-*/%=<>!&|^~?]+)|([{}()[\];,.:])/g

const BASH_PATTERN =
	/(#[^\n]*)|('[^']*'|"(?:\\.|[^"\\])*")|(\$\{[^}]+\}|\$[A-Za-z_]\w*|\$[#@*?$!0-9])|(-{1,2}[A-Za-z][\w-]*)|(\b\d+\b)|([A-Za-z_][\w-]*)|([{}()[\];,&|<>])/g

const tokenizeJsLike = (code: string, isTs: boolean): Token[] => {
	const tokens: Token[] = []
	let last = 0
	let match: RegExpExecArray | null
	JS_PATTERN.lastIndex = 0
	while ((match = JS_PATTERN.exec(code))) {
		if (match.index > last) {
			tokens.push({ type: 'plain', value: code.slice(last, match.index) })
		}
		const [full, comment, str, num, ident, op, punct] = match
		if (comment !== undefined) {
			tokens.push({ type: 'comment', value: comment })
		} else if (str !== undefined) {
			tokens.push({ type: 'string', value: str })
		} else if (num !== undefined) {
			tokens.push({ type: 'number', value: num })
		} else if (ident !== undefined) {
			if (JS_KEYWORDS.has(ident) || (isTs && TS_KEYWORDS.has(ident))) {
				tokens.push({ type: 'keyword', value: ident })
			} else if (JS_LITERALS.has(ident) || (isTs && TS_TYPES.has(ident))) {
				tokens.push({ type: 'literal', value: ident })
			} else if (code.charAt(match.index + ident.length) === '(') {
				tokens.push({ type: 'function', value: ident })
			} else {
				tokens.push({ type: 'plain', value: ident })
			}
		} else if (op !== undefined) {
			tokens.push({ type: 'operator', value: op })
		} else if (punct !== undefined) {
			tokens.push({ type: 'punctuation', value: punct })
		}
		last = match.index + full.length
	}
	if (last < code.length) {
		tokens.push({ type: 'plain', value: code.slice(last) })
	}
	return tokens
}

const tokenizeBash = (code: string): Token[] => {
	const tokens: Token[] = []
	let last = 0
	let match: RegExpExecArray | null
	BASH_PATTERN.lastIndex = 0
	while ((match = BASH_PATTERN.exec(code))) {
		if (match.index > last) {
			tokens.push({ type: 'plain', value: code.slice(last, match.index) })
		}
		const [full, comment, str, variable, flag, num, ident, punct] = match
		if (comment !== undefined) {
			tokens.push({ type: 'comment', value: comment })
		} else if (str !== undefined) {
			tokens.push({ type: 'string', value: str })
		} else if (variable !== undefined) {
			tokens.push({ type: 'variable', value: variable })
		} else if (flag !== undefined) {
			tokens.push({ type: 'flag', value: flag })
		} else if (num !== undefined) {
			tokens.push({ type: 'number', value: num })
		} else if (ident !== undefined) {
			if (BASH_KEYWORDS.has(ident)) {
				tokens.push({ type: 'keyword', value: ident })
			} else if (BASH_BUILTINS.has(ident)) {
				tokens.push({ type: 'function', value: ident })
			} else {
				tokens.push({ type: 'plain', value: ident })
			}
		} else if (punct !== undefined) {
			tokens.push({ type: 'punctuation', value: punct })
		}
		last = match.index + full.length
	}
	if (last < code.length) {
		tokens.push({ type: 'plain', value: code.slice(last) })
	}
	return tokens
}

const tokenize = (code: string, language: CodeSnippetLanguage): Token[] => {
	if (language === 'bash') return tokenizeBash(code)
	return tokenizeJsLike(code, language === 'typescript')
}

export const CodeSnippet: React.FC<CodeSnippetProps> = ({
	code,
	language = 'javascript',
	onCopy,
	showCopyButton = true,
	title,
	loading = false,
	className = '',
	...rest
}) => {
	const [copied, setCopied] = useState(false)

	const handleCopy = useCallback(() => {
		onCopy?.(code)
		setCopied(true)
		const id = window.setTimeout(() => setCopied(false), 2000)
		return () => window.clearTimeout(id)
	}, [code, onCopy])

	const tokens = useMemo(() => (loading ? [] : tokenize(code, language)), [code, language, loading])

	const rootClass = `component component-code-snippet component-code-snippet--${language} ${className}`.trim()

	if (loading) {
		return (
			<div className={rootClass} {...rest}>
				<div className="component-code-snippet__header">
					<Skeleton width="30%" />
				</div>
				<div className="component-code-snippet__body">
					<Skeleton count={4} />
				</div>
			</div>
		)
	}

	return (
		<div className={rootClass} {...rest}>
			<div className="component-code-snippet__header">
				<span className="component-code-snippet__language">
					{title || languageLabels[language]}
				</span>
				{showCopyButton && (
					<button
						type="button"
						className="component-code-snippet__copy"
						onClick={handleCopy}
						aria-label="Copy code"
					>
						<Icon name={copied ? 'check-lg' : 'clipboard'} />
						<span className="component-code-snippet__copy-label">
							{copied ? 'Copied!' : 'Copy'}
						</span>
					</button>
				)}
			</div>
			<pre className="component-code-snippet__pre">
				<code className="component-code-snippet__code">
					{tokens.map((token, i) =>
						token.type === 'plain' ? (
							<Fragment key={i}>{token.value}</Fragment>
						) : (
							<span
								key={i}
								className={`component-code-snippet__token component-code-snippet__token--${token.type}`}
							>
								{token.value}
							</span>
						)
					)}
				</code>
			</pre>
		</div>
	)
}
