// react-components/src/NewsletterSignup.tsx
import React, { useId, useState } from 'react'
import { Icon } from './Icon'

export interface NewsletterSignupProps extends Omit<React.HTMLAttributes<HTMLDivElement>, 'onSubmit' | 'title'> {
	onSubmit: (email: string) => Promise<void> | void
	placeholder?: string
	ctaLabel?: string
	successMessage?: string
	privacyHref?: string
	title?: React.ReactNode
	description?: React.ReactNode
}

type Status = 'idle' | 'submitting' | 'success' | 'error'

export const NewsletterSignup: React.FC<NewsletterSignupProps> = ({
	onSubmit,
	placeholder = 'you@example.com',
	ctaLabel = 'Subscribe',
	successMessage = 'Thanks! Check your inbox to confirm.',
	privacyHref,
	title,
	description,
	className = '',
	...rest
}) => {
	const inputId = useId()
	const [email, setEmail] = useState('')
	const [status, setStatus] = useState<Status>('idle')
	const [error, setError] = useState<string | null>(null)

	const handleSubmit = async (e: React.FormEvent) => {
		e.preventDefault()
		// Enter in the input bypasses the disabled CTA — apply the same guard here.
		if (!email.trim() || status === 'submitting') return
		setStatus('submitting')
		setError(null)
		try {
			await onSubmit(email.trim())
			setStatus('success')
			setEmail('')
		} catch (err) {
			setStatus('error')
			setError(err instanceof Error ? err.message : 'Something went wrong')
		}
	}

	const rootClass = `component component-newsletter-signup ${className}`.trim()

	return (
		<div className={rootClass} {...rest}>
			{title ? <h3 className="component-newsletter-signup__title">{title}</h3> : null}
			{description ? (
				<p className="component-newsletter-signup__description">{description}</p>
			) : null}
			{status === 'success' ? (
				<div className="component-newsletter-signup__success" role="status">
					<Icon name="check-circle-fill" aria-hidden={true} />
					{successMessage}
					<button
						type="button"
						className="component-newsletter-signup__reset"
						onClick={() => setStatus('idle')}
					>
						Subscribe another email
					</button>
				</div>
			) : (
				<form className="component-newsletter-signup__form" onSubmit={handleSubmit} noValidate>
					<label htmlFor={inputId} className="component-newsletter-signup__label">
						Email address
					</label>
					<div className="component-newsletter-signup__row">
						<input
							id={inputId}
							type="email"
							required
							value={email}
							onChange={(e) => setEmail(e.target.value)}
							placeholder={placeholder}
							disabled={status === 'submitting'}
							className="component-newsletter-signup__input"
						/>
						<button
							type="submit"
							className="component-newsletter-signup__cta"
							disabled={status === 'submitting' || !email}
						>
							{status === 'submitting' ? '…' : ctaLabel}
						</button>
					</div>
					{privacyHref ? (
						<p className="component-newsletter-signup__privacy">
							We respect your privacy.{' '}
							<a href={privacyHref} target="_blank" rel="noopener noreferrer">
								Read our privacy policy
							</a>
							.
						</p>
					) : null}
					{error ? (
						<p className="component-newsletter-signup__error" role="alert">{error}</p>
					) : null}
				</form>
			)}
		</div>
	)
}

export default NewsletterSignup

// web-components/src/NewsletterSignup.ts
import { lucideByName } from './internal/lucide'
import { esc } from './internal/esc'

const TAG_NAME = 'tc-newsletter-signup'

let _idCounter = 0

const mailCheckIconHtml = lucideByName('mail-check')

type Status = 'idle' | 'submitting' | 'success' | 'error'

export class NewsletterSignup extends HTMLElement {
    private _initialised = false
    private _status: Status = 'idle'
    private _email = ''
    private _error = ''
    private _idPrefix: string

    /** Optional callback fired alongside the tc-submit CustomEvent. May return a Promise. */
    onSubmit: ((email: string) => Promise<void> | void) | null = null

    constructor() {
        super()
        this._idPrefix = `tc-ns-${++_idCounter}`
    }

    static get observedAttributes(): string[] {
        return [
            // NOTE: 'title' is listed so attributeChangedCallback fires on changes.
            // No getter/setter defined — HTMLElement already reflects title natively.
            'title',
            'description',
            'placeholder',
            'cta-label',
            'success-message',
            'privacy-href',
        ]
    }

    connectedCallback(): void {
        if (!this._initialised) {
            this.render()
            this._initialised = true
        }
        this.addEventListener('input', this._onInput)
        this.addEventListener('submit', this._onFormSubmit)
    }

    disconnectedCallback(): void {
        this.removeEventListener('input', this._onInput)
        this.removeEventListener('submit', this._onFormSubmit)
    }

    attributeChangedCallback(): void {
        if (!this.isConnected || !this._initialised) return
        const emailFocused = document.activeElement === this.querySelector('input[type="email"]')
        this.render()
        if (emailFocused) {
            this.querySelector<HTMLInputElement>('input[type="email"]')?.focus()
        }
    }

    // NOTE: 'title' getter/setter deliberately omitted — HTMLElement already
    // exposes a native .title property that reflects the 'title' attribute.
    // Read via getAttribute('title') inside render().

    get description(): string | null {
        return this.getAttribute('description')
    }
    set description(v: string | null) {
        if (v != null) this.setAttribute('description', v)
        else this.removeAttribute('description')
    }

    get placeholder(): string {
        return this.getAttribute('placeholder') ?? 'you@example.com'
    }
    set placeholder(v: string) {
        this.setAttribute('placeholder', v)
    }

    get ctaLabel(): string {
        return this.getAttribute('cta-label') ?? 'Subscribe'
    }
    set ctaLabel(v: string) {
        this.setAttribute('cta-label', v)
    }

    get successMessage(): string {
        return this.getAttribute('success-message') ?? 'Thanks for subscribing!'
    }
    set successMessage(v: string) {
        this.setAttribute('success-message', v)
    }

    get privacyHref(): string | null {
        return this.getAttribute('privacy-href')
    }
    set privacyHref(v: string | null) {
        if (v != null) this.setAttribute('privacy-href', v)
        else this.removeAttribute('privacy-href')
    }

    private _onInput = (e: Event): void => {
        const input = e.target as HTMLInputElement
        if (input.type !== 'email') return
        this._email = input.value
        if (!this._error) return
        // Clear the validation error surgically — no full re-render needed.
        this._error = ''
        const errorEl = this.querySelector('.tc-newsletter-signup-error')
        if (errorEl) errorEl.textContent = ''
        input.removeAttribute('aria-invalid')
        input.removeAttribute('aria-describedby')
    }

    private _onFormSubmit = (e: Event): void => {
        e.preventDefault()
        if (this._status === 'submitting') return

        const inputEl = this.querySelector<HTMLInputElement>('input[type="email"]')
        const email = (inputEl?.value ?? this._email).trim()
        this._email = email

        if (!email || !inputEl?.validity.valid) {
            this._error = 'Please enter a valid email address.'
            const errorId = `${this._idPrefix}-error`
            const errorEl = this.querySelector(`#${errorId}`)
            if (errorEl) errorEl.textContent = this._error
            if (inputEl) {
                inputEl.setAttribute('aria-invalid', 'true')
                inputEl.setAttribute('aria-describedby', errorId)
                inputEl.focus()
            }
            return
        }

        this._error = ''
        this._status = 'submitting'
        this.render()

        this.dispatchEvent(
            new CustomEvent('tc-submit', {
                bubbles: true,
                composed: true,
                detail: { email },
            }),
        )

        const handleSuccess = (): void => {
            if (!this.isConnected) return
            this._status = 'success'
            this.render()
            const successEl = this.querySelector<HTMLElement>('.tc-newsletter-signup-success')
            if (successEl) {
                successEl.setAttribute('tabindex', '-1')
                successEl.focus()
            }
        }

        const handleError = (err?: unknown): void => {
            if (!this.isConnected) return
            const msg =
                err instanceof Error && err.message
                    ? err.message
                    : 'Something went wrong. Please try again.'
            this._error = msg
            this._status = 'error'
            this.render()
            this.querySelector<HTMLInputElement>('input[type="email"]')?.focus()
        }

        const promise = typeof this.onSubmit === 'function' ? this.onSubmit(email) : undefined

        if (promise instanceof Promise) {
            promise.then(handleSuccess, handleError)
        } else {
            handleSuccess()
        }
    }

    private render(): void {
        const titleText = this.getAttribute('title')
        const description = this.getAttribute('description')
        const placeholder = this.placeholder
        const ctaLabel = this.ctaLabel
        const successMessage = this.successMessage
        const privacyHref = this.privacyHref
        const inputId = `${this._idPrefix}-email`
        const errorId = `${this._idPrefix}-error`
        const status = this._status

        this.classList.add('tc-newsletter-signup')

        const titleHtml = titleText
            ? `<h2 class="tc-newsletter-signup-title">${esc(titleText)}</h2>`
            : ''

        const descriptionHtml = description
            ? `<p class="tc-newsletter-signup-description">${esc(description)}</p>`
            : ''

        let bodyHtml: string

        if (status === 'success') {
            bodyHtml = `
                <div class="tc-newsletter-signup-success" aria-live="polite" aria-atomic="true">
                    <span class="tc-newsletter-signup-success-icon" aria-hidden="true">${mailCheckIconHtml}</span>
                    <span class="tc-newsletter-signup-success-message">${esc(successMessage)}</span>
                </div>`
        } else {
            const isSubmitting = status === 'submitting'
            const disabledAttr = isSubmitting ? ' disabled' : ''
            const ariaInvalidAttr = this._error ? ' aria-invalid="true"' : ''
            const ariaDescAttr = this._error ? ` aria-describedby="${errorId}"` : ''

            const submitContent = isSubmitting
                ? `<span class="tc-newsletter-signup-spinner" role="status" aria-label="Submitting…"></span>`
                : esc(ctaLabel)

            const privacyHtml = privacyHref
                ? `<a href="${esc(privacyHref)}" class="tc-newsletter-signup-privacy" target="_blank" rel="noopener noreferrer">Privacy policy</a>`
                : ''

            bodyHtml = `
                <form class="tc-newsletter-signup-form" novalidate>
                    <label class="visually-hidden" for="${inputId}">Email address</label>
                    <input
                        id="${inputId}"
                        type="email"
                        class="tc-newsletter-signup-input"
                        placeholder="${esc(placeholder)}"
                        value="${esc(this._email)}"
                        autocomplete="email"
                        required${ariaInvalidAttr}${ariaDescAttr}${disabledAttr}
                    />
                    <button
                        type="submit"
                        class="tc-newsletter-signup-submit"${disabledAttr}
                    >${submitContent}</button>
                    <p id="${errorId}" class="tc-newsletter-signup-error" aria-live="assertive" aria-atomic="true">${this._error ? esc(this._error) : ''}</p>
                    ${privacyHtml}
                </form>`
        }

        this.innerHTML = `
            <div class="tc-newsletter-signup-inner">
                ${titleHtml}
                ${descriptionHtml}
                ${bodyHtml}
            </div>`
    }
}

declare global {
    interface HTMLElementTagNameMap {
        [TAG_NAME]: NewsletterSignup
    }
}
