// react-components/src/ScoringRules.tsx
import React from 'react'

export interface ScoringRule {
	icon?: React.ReactNode
	title: React.ReactNode
	description: React.ReactNode
	points: React.ReactNode
	suffix?: React.ReactNode
	accent?: 'pink' | 'yellow' | 'cyan' | 'green' | 'red'
}

export interface ScoringRulesProps extends React.HTMLAttributes<HTMLDivElement> {
	rules: ScoringRule[]
}

export const ScoringRules: React.FC<ScoringRulesProps> = ({
	rules,
	className = '',
	...rest
}) => {
	return (
		<div className={`component component-scoring-rules ${className}`.trim()} {...rest}>
			{rules.map((r, i) => (
				<div
					key={i}
					className={[
						'component-scoring-rules__row',
						r.accent ? `component-scoring-rules__row--${r.accent}` : '',
					].filter(Boolean).join(' ')}
				>
					<div className="component-scoring-rules__icon" aria-hidden={true}>{r.icon}</div>
					<div className="component-scoring-rules__body">
						<div className="component-scoring-rules__title">{r.title}</div>
						<div className="component-scoring-rules__desc">{r.description}</div>
					</div>
					<div className="component-scoring-rules__pts">
						{r.points}
						{r.suffix && <em className="component-scoring-rules__suffix">{r.suffix}</em>}
					</div>
				</div>
			))}
		</div>
	)
}

// web-components/src/ScoringRules.ts
import { lucideByName } from './internal/lucide'
import { esc } from './internal/esc'

const TAG_NAME = 'tc-scoring-rules'

export type ScoringRuleAccent = 'pink' | 'yellow' | 'cyan' | 'green' | 'red'
const ACCENTS: ScoringRuleAccent[] = ['pink', 'yellow', 'cyan', 'green', 'red']

export interface ScoringRule {
    icon?: string
    title: string
    description: string
    points: string
    suffix?: string
    accent?: ScoringRuleAccent
}

export class ScoringRules extends HTMLElement {
    private _initialised = false
    private _rules: ScoringRule[] = []

    static get observedAttributes(): string[] {
        return []
    }

    connectedCallback(): void {
        if (!this._initialised) {
            this.render()
            this._initialised = true
        }
    }

    get rules(): ScoringRule[] {
        return this._rules
    }
    set rules(v: ScoringRule[]) {
        this._rules = Array.isArray(v) ? v : []
        if (this._initialised) this.render()
    }

    private render(): void {
        this.classList.add('tc-scoring-rules')
        this.setAttribute('role', 'list')

        this.innerHTML = this._rules
            .map((rule) => {
                const accentClass =
                    rule.accent && (ACCENTS as string[]).includes(rule.accent)
                        ? ` tc-accent-${rule.accent}`
                        : ''

                const iconHtml = rule.icon
                    ? `<span class="tc-scoring-rule-icon" aria-hidden="true">${lucideByName(rule.icon)}</span>`
                    : ''

                const suffixHtml = rule.suffix
                    ? `<span class="tc-scoring-rule-suffix">${esc(rule.suffix)}</span>`
                    : ''

                return `<div class="tc-scoring-rule${accentClass}" role="listitem">${iconHtml}<div class="tc-scoring-rule-body"><div class="tc-scoring-rule-title">${esc(rule.title)}</div><div class="tc-scoring-rule-desc">${esc(rule.description)}</div></div><div class="tc-scoring-rule-points">${esc(rule.points)}${suffixHtml}</div></div>`
            })
            .join('')
    }
}

declare global {
    interface HTMLElementTagNameMap {
        [TAG_NAME]: ScoringRules
    }
}
