// react-components/src/Timeline.tsx
import type { CSSProperties, FC, HTMLAttributes, ReactNode } from 'react'
import { Skeleton } from './Skeleton'

export type TimelineVariant = 'default' | 'glass' | 'outlined' | 'elevated' | 'minimal'
export type TimelineConnector = 'gradient' | 'solid' | 'dashed'
export type TimelineStatus = 'completed' | 'active' | 'upcoming'

export interface TimelineItem {
	title: string
	date: string
	description?: string
	side?: 'left' | 'right'
	subtitle?: string
	badge?: string
	meta?: string
	icon?: ReactNode
	actions?: ReactNode
	status?: TimelineStatus
	overlap?: number
	tags?: string[]
	progress?: number
	accentColor?: string
}

export interface TimelineProps extends HTMLAttributes<HTMLDivElement> {
	items: TimelineItem[]
	overlap?: number
	loading?: boolean
	loadingCount?: number
	variant?: TimelineVariant
	connector?: TimelineConnector
}

export const Timeline: FC<TimelineProps> = ({
	items,
	overlap,
	loading = false,
	loadingCount = 3,
	variant = 'default',
	connector = 'gradient',
	className,
	...rest
}) => {
	const rootClasses = [
		'component component-timeline',
		`component-timeline--${variant}`,
		`component-timeline--connector-${connector}`,
		className,
	]
		.filter(Boolean)
		.join(' ')

	if (loading) {
		return (
			<div className={rootClasses} {...rest}>
				<div className="component-timeline__line" aria-hidden="true" />
				<div className="component-timeline__items">
					{Array.from({ length: loadingCount }, (_, i) => (
						<div
							key={i}
							className={`component-timeline__item component-timeline__item--${i % 2 === 0 ? 'left' : 'right'}`}
						>
							<div className="component-timeline__dot" aria-hidden="true" />
							<article className="component-timeline__card card" style={{ padding: '1.25rem' }}>
								<Skeleton width="30%" />
								<Skeleton width="60%" height="1.25em" />
								<Skeleton count={2} />
							</article>
						</div>
					))}
				</div>
			</div>
		)
	}

	return (
		<div className={rootClasses} {...rest}>
			<div className="component-timeline__line" aria-hidden="true" />
			<div className="component-timeline__items">
				{items.map((item, index) => {
					const side = item.side ?? (index % 2 === 0 ? 'left' : 'right')
					const status = item.status ?? (index === 0 ? 'active' : 'upcoming')
					const overlapValue = index === 0 ? 0 : (item.overlap ?? overlap ?? 0)
					const itemClasses = [
						'component-timeline__item',
						`component-timeline__item--${side}`,
						`component-timeline__item--${status}`,
					]

					if (overlapValue > 0) {
						itemClasses.push('component-timeline__item--overlap')
					}

					const itemStyle: CSSProperties = {}
					if (overlapValue > 0) {
						(itemStyle as Record<string, string>)['--timeline-item-overlap'] = `${overlapValue}px`
					}
					if (item.accentColor) {
						(itemStyle as Record<string, string>)['--tl-item-accent'] = item.accentColor
					}

					const progress =
						typeof item.progress === 'number'
							? Math.max(0, Math.min(100, item.progress))
							: undefined

					return (
						<div
							key={`${item.title}-${item.date}-${index}`}
							className={itemClasses.join(' ')}
							aria-current={status === 'active' ? 'step' : undefined}
							style={Object.keys(itemStyle).length > 0 ? itemStyle : undefined}
						>
							<div className="component-timeline__dot" aria-hidden="true">
								<span className="component-timeline__dot-pulse" aria-hidden="true" />
								<span className="component-timeline__dot-ring" aria-hidden="true" />
							</div>
							<article className="component-timeline__card card">
								<header className="component-timeline__header">
									<div className="component-timeline__meta">
										<span className="component-timeline__date">{item.date}</span>
										{item.meta ? (
											<span className="component-timeline__meta-text">{item.meta}</span>
										) : null}
									</div>
									{item.badge ? (
										<span className="component-timeline__badge">{item.badge}</span>
									) : null}
								</header>
								<div className="component-timeline__title-group">
									{item.icon ? (
										<span className="component-timeline__icon" aria-hidden="true">
											{item.icon}
										</span>
									) : null}
									<div className="component-timeline__titles">
										<h4 className="component-timeline__title">{item.title}</h4>
										{item.subtitle ? (
											<p className="component-timeline__subtitle">{item.subtitle}</p>
										) : null}
									</div>
								</div>
								{item.description ? (
									<p className="component-timeline__description">{item.description}</p>
								) : null}
								{item.tags && item.tags.length > 0 ? (
									<div className="component-timeline__tags">
										{item.tags.map((tag, i) => (
											<span key={`${tag}-${i}`} className="component-timeline__tag">
												{tag}
											</span>
										))}
									</div>
								) : null}
								{progress !== undefined ? (
									<div
										className="component-timeline__progress"
										role="progressbar"
										aria-valuenow={progress}
										aria-valuemin={0}
										aria-valuemax={100}
									>
										<div
											className="component-timeline__progress-bar"
											style={{ width: `${progress}%` }}
										/>
									</div>
								) : null}
								{item.actions ? (
									<div className="component-timeline__actions">{item.actions}</div>
								) : null}
							</article>
						</div>
					)
				})}
			</div>
		</div>
	)
}

export default Timeline

// web-components/src/Timeline.ts
import { lucideByName } from './internal/lucide'
import { esc } from './internal/esc'

const TAG_NAME = 'tc-timeline'

export type TimelineVariant = 'default' | 'glass' | 'outlined' | 'elevated' | 'minimal'
export type TimelineConnector = 'gradient' | 'solid' | 'dashed'
export type TimelineStatus = 'completed' | 'active' | 'upcoming'

export interface TimelineItem {
    title: string
    date: string
    description?: string
    side?: 'left' | 'right'
    subtitle?: string
    badge?: string
    meta?: string
    icon?: string
    status?: TimelineStatus
    overlap?: number
    tags?: string[]
    progress?: number
    accentColor?: string
}

const VARIANTS: TimelineVariant[] = ['default', 'glass', 'outlined', 'elevated', 'minimal']
const CONNECTORS: TimelineConnector[] = ['gradient', 'solid', 'dashed']

export class Timeline extends HTMLElement {
    private _initialised = false
    private _items: TimelineItem[] = []

    static get observedAttributes(): string[] {
        return ['variant', 'connector', 'overlap', 'loading', 'loading-count']
    }

    connectedCallback(): void {
        if (!this._initialised) {
            this.render()
            this._initialised = true
        }
    }

    attributeChangedCallback(): void {
        if (!this.isConnected || !this._initialised) return
        this.render()
    }

    get items(): TimelineItem[] {
        return this._items
    }
    set items(v: TimelineItem[]) {
        this._items = Array.isArray(v) ? v : []
        if (this._initialised) this.render()
    }

    get variant(): TimelineVariant {
        const v = this.getAttribute('variant') as TimelineVariant
        return VARIANTS.includes(v) ? v : 'default'
    }
    set variant(v: TimelineVariant) {
        this.setAttribute('variant', v)
    }

    get connector(): TimelineConnector {
        const v = this.getAttribute('connector') as TimelineConnector
        return CONNECTORS.includes(v) ? v : 'gradient'
    }
    set connector(v: TimelineConnector) {
        this.setAttribute('connector', v)
    }

    get overlap(): number {
        return parseInt(this.getAttribute('overlap') ?? '0', 10) || 0
    }
    set overlap(v: number) {
        this.setAttribute('overlap', String(v))
    }

    get loading(): boolean {
        return this.hasAttribute('loading')
    }
    set loading(v: boolean) {
        if (v) this.setAttribute('loading', '')
        else this.removeAttribute('loading')
    }

    get loadingCount(): number {
        return Math.max(1, parseInt(this.getAttribute('loading-count') ?? '3', 10) || 3)
    }
    set loadingCount(v: number) {
        this.setAttribute('loading-count', String(v))
    }

    private _renderNode(item: TimelineItem, status: TimelineStatus): string {
        if (item.icon) {
            return (
                `<div class="tc-timeline-node tc-timeline-node--icon" aria-hidden="true">` +
                lucideByName(item.icon) +
                `</div>`
            )
        }
        return (
            `<div class="tc-timeline-node tc-timeline-node--dot tc-timeline-node--${status}" aria-hidden="true">` +
            `<span class="tc-timeline-node-dot"></span>` +
            `</div>`
        )
    }

    private _renderItem(item: TimelineItem, index: number): string {
        const side = item.side ?? (index % 2 === 0 ? 'left' : 'right')
        const status = item.status ?? (index === 0 ? 'active' : 'upcoming')
        const globalOverlap = this.overlap
        const overlapValue = index === 0 ? 0 : (item.overlap ?? globalOverlap)

        const classes = `tc-timeline-item tc-timeline-item--${status} tc-timeline-item--${side}`

        const styleParts: string[] = [`--tl-index: ${index}`]
        if (overlapValue > 0) {
            styleParts.push(`--timeline-item-overlap: ${overlapValue}px`)
        }
        if (item.accentColor) {
            styleParts.push(`--tl-item-accent: ${esc(item.accentColor)}`)
        }
        const styleAttr = ` style="${styleParts.join('; ')}"`

        const ariaCurrent = status === 'active' ? ' aria-current="step"' : ''
        const nodeHtml = this._renderNode(item, status)

        const badgeHtml = item.badge
            ? `<span class="tc-timeline-badge">${esc(item.badge)}</span>`
            : ''

        const metaHtml = item.meta ? `<span class="tc-timeline-meta">${esc(item.meta)}</span>` : ''

        const subtitleHtml = item.subtitle
            ? `<p class="tc-timeline-subtitle">${esc(item.subtitle)}</p>`
            : ''

        const descHtml = item.description
            ? `<p class="tc-timeline-description">${esc(item.description)}</p>`
            : ''

        const tagsHtml =
            item.tags && item.tags.length > 0
                ? `<div class="tc-timeline-tags">${item.tags.map((t) => `<span class="tc-timeline-tag">${esc(t)}</span>`).join('')}</div>`
                : ''

        const progressNum =
            typeof item.progress === 'number' ? Math.max(0, Math.min(100, item.progress)) : null
        const progressHtml =
            progressNum !== null
                ? `<div class="tc-timeline-progress" role="progressbar" aria-valuenow="${progressNum}" aria-valuemin="0" aria-valuemax="100">` +
                  `<div class="tc-timeline-progress-bar" style="width: ${progressNum}%"></div>` +
                  `</div>`
                : ''

        return (
            `<li class="${classes}"${styleAttr}${ariaCurrent}>` +
            nodeHtml +
            `<article class="tc-timeline-card">` +
            `<header class="tc-timeline-header">` +
            `<div class="tc-timeline-meta-row">` +
            `<time class="tc-timeline-date">${esc(item.date)}</time>` +
            metaHtml +
            `</div>` +
            badgeHtml +
            `</header>` +
            `<h4 class="tc-timeline-title">${esc(item.title)}</h4>` +
            subtitleHtml +
            descHtml +
            tagsHtml +
            progressHtml +
            `</article>` +
            `</li>`
        )
    }

    private render(): void {
        const variant = this.variant
        const connector = this.connector
        const loading = this.loading

        const lineHtml = `<div class="tc-timeline-line tc-timeline-line--${connector}" aria-hidden="true"></div>`

        let itemsHtml: string
        if (loading) {
            const count = this.loadingCount
            const rows = Array.from({ length: count }, (_, i) => {
                const side = i % 2 === 0 ? 'left' : 'right'
                return (
                    `<li class="tc-timeline-item tc-timeline-item--skeleton tc-timeline-item--${side}" aria-hidden="true">` +
                    `<div class="tc-timeline-node tc-timeline-node--dot tc-timeline-node--skeleton" aria-hidden="true">` +
                    `<span class="tc-timeline-node-dot"></span>` +
                    `</div>` +
                    `<article class="tc-timeline-card tc-timeline-card--skeleton">` +
                    `<div class="tc-timeline-skeleton tc-timeline-skeleton--date"></div>` +
                    `<div class="tc-timeline-skeleton tc-timeline-skeleton--title"></div>` +
                    `<div class="tc-timeline-skeleton tc-timeline-skeleton--desc"></div>` +
                    `</article>` +
                    `</li>`
                )
            }).join('')
            itemsHtml =
                `<ol class="tc-timeline-items" aria-busy="true">` +
                `<li class="visually-hidden" role="status">Loading timeline…</li>` +
                rows +
                `</ol>`
        } else {
            const items = this._items.map((item, i) => this._renderItem(item, i)).join('')
            itemsHtml = `<ol class="tc-timeline-items">${items}</ol>`
        }

        this.innerHTML =
            `<div class="tc-timeline tc-timeline--${variant}">` + lineHtml + itemsHtml + `</div>`
    }
}

declare global {
    interface HTMLElementTagNameMap {
        [TAG_NAME]: Timeline
    }
}
